services: 
  postgres:
    image: bitnami/postgresql:latest
    container_name: pg
    environment:
      POSTGRES_DB=${POSTGRES_DB}
      POSTGRES_USER=${USER}
      POSTGRES_PASSWORD=${PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    networks:
      - analytics
  
  redash:
    image: redash/redash:25.8.0
    container_name: rsh
    environment:
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    networks:
      - analytics
  
  redis:
    image: redis:8.4.0
    container_name: redis
    networks:
      - analytics
    

volumes:
  postgres_data:

networks:
  analytics:
    driver: bridge